import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "../components/Navigation/navbar"
import { ThemeProvider } from "@/components/theme-provider";
import Mobilenav from "@/components/Navigation/mobile-nav";
import Footer from "@/components/Navigation/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn("relative text-muted-foreground overflow-x-hidden", geistSans.variable, geistMono.variable)}>
    <div className="flex flex-col min-h-screen">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <Mobilenav />
        
           <main className="flex-1 overflow-x-hidden">
            {children}
          </main>
          <Footer />
        </ThemeProvider>
        </div>
      </body>

    </html>
  );
}
